version: '3.7'

services:
  frontend:
    build: ./frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    build: ./backend

    ports:
      - "3001:3000"

    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      MYSQL_ROOT_PASSWORD: root

    networks:
      - default

volumes:
  db_data:

networks:
  default:
