name: Pack & Publish

on:
  push:
    branches: main

env:
    MIRROR_URL: git@github.com:EpitechPromo2027/B-SVR-500-BDX-5-1-survivor-ethan.thierry.git

jobs:

    build:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Frontend
              uses: docker/build-push-action@v6
              with:
                tags: frontend:latest
                context: ./frontend
                file: ./frontend/Dockerfile
                outputs: type=docker, dest=frontend.tar

            - name: Build Backend
              uses: docker/build-push-action@v6
              with:
                tags: backend:latest
                context: ./backend
                file: ./backend/Dockerfile
                outputs: type=docker, dest=backend.tar

            - name: Upload Frontend
              uses: actions/upload-artifact@v4
              with:
                name: frontend
                path: frontend.tar

            - name: Upload Backend
              uses: actions/upload-artifact@v4
              with:
                name: backend
                path: backend.tar

    delivery:
        runs-on: ubuntu-latest
        needs: build
        steps:

            - name: Download Frontend
              uses: actions/download-artifact@v4
              with:
                name: frontend

            - name: Download Backend
              uses: actions/download-artifact@v4
              with:
                name: backend

            - name: Publish Images to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.FG_TOKEN }}

    mirror:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: main

            - name: Push to Mirror
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url: ${{ env.MIRROR_URL }}
                ssh_private_key: ${{ secrets.SSH_KEY }}


