name: Pack & Publish

on:
  push:
    branches: main

env:
    MIRROR_URL: git@github.com:EpitechPromo2027/B-SVR-500-BDX-5-1-survivor-ethan.thierry.git

jobs:

    build:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.FG_TOKEN }}

            - name: Build Frontend
              run: |
                docker build -t frontend:latest ./frontend
                docker tag frontend:latest ghcr.io/ichiidev/survivor-frontend:latest
                docker push ghcr.io/ichiidev/survivor-frontend:latest

            - name: Build Backend
              run: |
                docker build -t backend:latest ./backend
                docker tag backend:latest ghcr.io/ichiidev/survivor-backend:latest
                docker push ghcr.io/ichiidev/survivor-backend:latest

    mirror:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: main

            - name: Push to Mirror
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url: ${{ env.MIRROR_URL }}
                ssh_private_key: ${{ secrets.SSH_KEY }}


